apiVersion: 1

datasources:
  - name: Sky-Krono-Prometheus
    type: prometheus
    # Access mode - proxy (server in the UI) or direct (browser in the UI).
    access: proxy
    url: http://host.docker.internal:9090
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      # prometheusVersion: 2.37.0